# version: '3.8'

networks:
  transcendence:
    driver: bridge


services:
  django:
      container_name: container_user_managemant
      build:
        context: ./services/user_management/
        dockerfile: Dockerfile
      depends_on:
        - postgres
        - redis
      image: image_python
      restart: always
      networks:
        - transcendence
      expose:
        - "8000"
      ports:
        - "8000:8000"
      env_file:
      - .env
      volumes:
      - ./services/user_management/app_user_management:/app


  redis:
      container_name: container_redis
      build:
        context: ./services/redis/
        dockerfile: Dockerfile
      image: redis
      restart: always
      networks:
        - transcendence
      expose:
        - "6379"
      env_file:
      - .env

  postgres:
      container_name: container_postgres
      build:
        context: ./services/postgres/
        dockerfile: Dockerfile
      image: postgres
      restart: always
      networks:
        - transcendence
      expose:
        - "5432"
      env_file:
      - .env
      volumes:
      - ./services/postgres/postgresql_data:/var/lib/postgresql/data

# docker rmi $(docker images -q)
# docker rm -f $(docker ps -aq)
# docker volume prune
