# Generated by Django 4.2.16 on 2024-10-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0005_customuser_code_verification_delete_onetimepassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='code_verification',
            new_name='code_opt',
        ),
    ]
