# Generated by Django 4.2.16 on 2024-11-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0012_customuser_username_42'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='code_opt',
            new_name='code_otp',
        ),
    ]
