# Generated by Django 4.2.16 on 2024-10-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nickname',
            new_name='username',
        ),
    ]
