# Generated by Django 4.2.16 on 2024-10-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0004_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_verification',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
