# Generated by Django 4.2.16 on 2024-11-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0020_remove_customuser_user_42'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
