# Generated by Django 4.2.16 on 2024-10-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0007_customuser_active_2fa_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
