# Generated by Django 4.2.16 on 2024-10-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0009_remove_customuser_image_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_42',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
