# Generated by Django 4.2.16 on 2024-10-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0010_customuser_user_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged_2fa',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
