# Generated by Django 4.2.16 on 2024-11-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0013_rename_code_opt_customuser_code_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, default='avatars/default_avatar.png', max_length=255, null=True),
        ),
    ]
