"""
Django settings for transcendence project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os



BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('Debug')
EMAIL_PASSWORD = os.getenv('EMAIL_PASSWORD')
ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # Ajoute ton nom de domaine ou adresse IP ici si nécessaire


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'user_managemanet',
]

AUTH_USER_MODEL = 'user_managemanet.CustomUser'

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',  # Peut rester commenté si non utilisé
    'django.contrib.sessions.middleware.SessionMiddleware',  # Gère les sessions
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Middleware d'authentification
    'django.contrib.messages.middleware.MessageMiddleware',  # Gère les messages
    'user_managemanet.middleware.DisableCSRF',
    'user_managemanet.middleware.JWTAuthenticationMiddleware',  # Votre middleware d'authentification JWT
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Protection CSRF
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Peut rester commenté si non utilisé
]






ROOT_URLCONF = 'transcendence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcendence.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'transcendence',
#         'USER': 'admindb',
#         'PASSWORD': '0000',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': "transcendence",
#         'USER':"ymaaloum",
#         'PASSWORD': "0000",
#         'HOST' :'container_postgres',
#         # 'HOST' : '172.18.0.2',
#         'PORT': '5432',
#     }
# }




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': 'ymaaloum',
#         'PASSWORD': '00000',
#         'HOST' : ,
#         'PORT': '5432',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



CLIENT_ID_42=os.getenv('CLIENT_ID_42')
CLIENT_SECRET_42=os.getenv('CLIENT_SECRET_42')
REDIRECT_URI_42='http://localhost:8000/callback/'
CLIENT_ID_GOOGLE=os.getenv('CLIENT_ID_GOOGLE')
CLIENT_SECRET_GOOGLE=os.getenv('CLIENT_SECRET_GOOGLE')
REDIRECT_URI_GOOGLE="http://localhost:8000/oauth/callback/"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/'media/'






CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Use in-memory channel layer
    },
}


CORS_ALLOW_HEADERS = [
    'content-type',
    'accept',
    'Authorization',
    'X-Requested-With',
]


# REST_FRAMEWORK = {
#     'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',  # Use JSON instead of HTML
#     ),
# }




CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5501", # Adjust according to where your frontend is served
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True


ASGI_APPLICATION = "transcendence.asgi.application"
WSGI_APPLICATION = 'transcendence.wsgi.application'