# Generated by Django 4.2.16 on 2024-11-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Connected',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
